package com.all.weather;

import java.util.HashMap;
import java.util.Map;

import com.all.weather.R;


class AccuIconMapper {
	private static Map<Integer, String> iconNamesMap = new HashMap<Integer, String>();
	private static Map<String, Integer> cityNamesMap = new HashMap<String, Integer>();
	private static Map<Integer, Integer> icondescript = new HashMap<Integer, Integer>();
	private static Map<Integer, Integer> iconsMap = new HashMap<Integer, Integer>();
	private static Map<String, Integer> weekiconsMap = new HashMap<String, Integer>();
	private static Map<Character, Integer> digit_iconsMap = new HashMap<Character, Integer>();
	static {
        cityNamesMap.put("Harbin", R.string.haerbin);
	    cityNamesMap.put("China", R.string.china);
		cityNamesMap.put("Songjiang", R.string.songjiang);
		cityNamesMap.put("Qitaihe", R.string.qitaihe);
		cityNamesMap.put("Liling", R.string.liling);
		cityNamesMap.put("Fuling", R.string.fuling);
		cityNamesMap.put("Gongzhuling", R.string.gongzhuling);
		cityNamesMap.put("Shexian", R.string.shexian);
		cityNamesMap.put("Xinghua", R.string.xinghua);
		cityNamesMap.put("Beijing", R.string.beijing);
		cityNamesMap.put("Shanghai", R.string.shanghai);
		cityNamesMap.put("Tianjin", R.string.tianjin);
		cityNamesMap.put("Chongqing", R.string.chongqing);
		cityNamesMap.put("Akesu", R.string.akesu);
		cityNamesMap.put("Anning", R.string.anning);
		cityNamesMap.put("Anqing", R.string.anqing);
		cityNamesMap.put("Anshan", R.string.anshan);
		cityNamesMap.put("Anshun", R.string.anshun);
		cityNamesMap.put("Anyang", R.string.anyang);
		cityNamesMap.put("Baicheng", R.string.baicheng);
		cityNamesMap.put("Baishan", R.string.baishan);
		cityNamesMap.put("Baiyin", R.string.baiyin);
		cityNamesMap.put("Bengbu", R.string.bengbu);
		cityNamesMap.put("Baoding", R.string.baoding);
		cityNamesMap.put("Baoji", R.string.baoji);
		cityNamesMap.put("Baoshan", R.string.baoshan);
		cityNamesMap.put("Bazhong", R.string.bazhong);
		cityNamesMap.put("Beihai", R.string.beihai);
		cityNamesMap.put("Benxi", R.string.benxi);
		cityNamesMap.put("Binzhou", R.string.binzhou);
		cityNamesMap.put("Bole", R.string.bole);
		cityNamesMap.put("Bozhou", R.string.bozhou);
		cityNamesMap.put("Cangzhou", R.string.cangzhou);
		cityNamesMap.put("Changde", R.string.changde);
		cityNamesMap.put("Changji", R.string.changji);
		cityNamesMap.put("Changshu", R.string.changshu);
		cityNamesMap.put("Changzhou", R.string.changzhou);
		cityNamesMap.put("Chaohu", R.string.chaohu);
		cityNamesMap.put("Chaoyang", R.string.chaoyang);
		cityNamesMap.put("Chaozhou", R.string.chaozhou);
		cityNamesMap.put("Chengde", R.string.chengde);
		cityNamesMap.put("Chengdu", R.string.chengdu);
		cityNamesMap.put("Chenggu", R.string.chenggu);
		cityNamesMap.put("Chenzhou", R.string.chenzhou);
		cityNamesMap.put("Chibi", R.string.chibi);
		cityNamesMap.put("Chifeng", R.string.chifeng);
		cityNamesMap.put("Chishui", R.string.chishui);
		cityNamesMap.put("Chizhou", R.string.chizhou);
		cityNamesMap.put("Chongzuo", R.string.chongzuo);
		cityNamesMap.put("Chuxiong", R.string.chuxiong);
		cityNamesMap.put("Chuzhou", R.string.chuzhou);
		cityNamesMap.put("Cixi", R.string.cixi);
		cityNamesMap.put("Conghua", R.string.conghua);
		cityNamesMap.put("Dali", R.string.dali);
		cityNamesMap.put("Dalian", R.string.dalian);
		cityNamesMap.put("Dandong", R.string.dandong);
		cityNamesMap.put("Danyang", R.string.danyang);
		cityNamesMap.put("Daqing", R.string.daqing);
		cityNamesMap.put("Datong", R.string.datong);
		cityNamesMap.put("Dazhou", R.string.dazhou);
		cityNamesMap.put("Deyang", R.string.deyang);
		cityNamesMap.put("Dezhou", R.string.dezhou);
		cityNamesMap.put("Dongguan", R.string.dongguan);
		cityNamesMap.put("Dongyang", R.string.dongyang);
		cityNamesMap.put("Dongying", R.string.dongying);
		cityNamesMap.put("Douyun", R.string.douyun);
		cityNamesMap.put("Dunhua", R.string.dunhua);
		cityNamesMap.put("Eerduosi", R.string.eerduosi);
		cityNamesMap.put("Enshi", R.string.enshi);
		cityNamesMap.put("Fangchenggang", R.string.fangchenggang);
		cityNamesMap.put("Feicheng", R.string.feicheng);
		cityNamesMap.put("Fenghua", R.string.fenghua);
		cityNamesMap.put("Fushun", R.string.fushun);
		cityNamesMap.put("Fuxin", R.string.fuxin);
		cityNamesMap.put("Fuyang", R.string.fuyang);
		cityNamesMap.put("Fuyang1", R.string.fuyang1);
		cityNamesMap.put("Fuzhou", R.string.fuzhou);
		cityNamesMap.put("Fuzhou1", R.string.fuzhou1);
		cityNamesMap.put("Ganyu", R.string.ganyu);
		cityNamesMap.put("Ganzhou", R.string.ganzhou);
		cityNamesMap.put("Gaoming", R.string.gaoming);
		cityNamesMap.put("Gaoyou", R.string.gaoyou);
		cityNamesMap.put("Geermu", R.string.geermu);
		cityNamesMap.put("Gejiu", R.string.gejiu);
		cityNamesMap.put("Gongyi", R.string.gongyi);
		cityNamesMap.put("Guangan", R.string.guangan);
		cityNamesMap.put("Guangyuan", R.string.guangyuan);
		cityNamesMap.put("Guangzhou", R.string.guangzhou);
		cityNamesMap.put("Gubaotou", R.string.gubaotou);
		cityNamesMap.put("Guigang", R.string.guigang);
		cityNamesMap.put("Guilin", R.string.guilin);
		cityNamesMap.put("Guiyang", R.string.guiyang);
		cityNamesMap.put("Guyuan", R.string.guyuan);
		cityNamesMap.put("Haerbin", R.string.haerbin);
		cityNamesMap.put("Haicheng", R.string.haicheng);
		cityNamesMap.put("Haikou", R.string.haikou);
		cityNamesMap.put("Haimen", R.string.haimen);
		cityNamesMap.put("Haining", R.string.haining);
		cityNamesMap.put("Hami", R.string.hami);
		cityNamesMap.put("Handan", R.string.handan);
		cityNamesMap.put("Hangzhou", R.string.hangzhou);
		cityNamesMap.put("Hanzhong", R.string.hanzhong);
		cityNamesMap.put("Hebi", R.string.hebi);
		cityNamesMap.put("Hefei", R.string.hefei);
		cityNamesMap.put("Hengshui", R.string.hengshui);
		cityNamesMap.put("Hengyang", R.string.hengyang);
		cityNamesMap.put("Hetian", R.string.hetian);
		cityNamesMap.put("Heyuan", R.string.heyuan);
		cityNamesMap.put("Heze", R.string.heze);
		cityNamesMap.put("Huadou", R.string.huadou);
		cityNamesMap.put("Huaian", R.string.huaian);
		cityNamesMap.put("Huaibei", R.string.huaibei);
		cityNamesMap.put("Huaihua", R.string.huaihua);
		cityNamesMap.put("Huainan", R.string.huainan);
		cityNamesMap.put("Huanggang", R.string.huanggang);
		cityNamesMap.put("Huangshan", R.string.huangshan);
		cityNamesMap.put("Huangshi", R.string.huangshi);
		cityNamesMap.put("Huhehaote", R.string.huhehaote);
		cityNamesMap.put("Huizhou", R.string.huizhou);
		cityNamesMap.put("Huludao", R.string.huludao);
		cityNamesMap.put("Huzhou", R.string.huzhou);
		cityNamesMap.put("Jiamusi", R.string.jiamusi);
		cityNamesMap.put("Jian", R.string.jian);
		cityNamesMap.put("Jiangdou", R.string.jiangdou);
		cityNamesMap.put("Jiangmen", R.string.jiangmen);
		cityNamesMap.put("Jiangyin", R.string.jiangyin);
		cityNamesMap.put("Jiaonan", R.string.jiaonan);
		cityNamesMap.put("Jiaozhou", R.string.jiaozhou);
		cityNamesMap.put("Jiaozuo", R.string.jiaozuo);
		cityNamesMap.put("Jiashan", R.string.jiashan);
		cityNamesMap.put("Jiaxing", R.string.jiaxing);
		cityNamesMap.put("Jiexiu", R.string.jiexiu);
		cityNamesMap.put("Jilin", R.string.jilin);
		cityNamesMap.put("Jimo", R.string.jimo);
		cityNamesMap.put("Jinan", R.string.jinan);
		cityNamesMap.put("Jincheng", R.string.jincheng);
		cityNamesMap.put("Jingdezhen", R.string.jingdezhen);
		cityNamesMap.put("Jinghong", R.string.jinghong);
		cityNamesMap.put("Jingjiang", R.string.jingjiang);
		cityNamesMap.put("Jingmen", R.string.jingmen);
		cityNamesMap.put("Jingzhou", R.string.jingzhou);
		cityNamesMap.put("Jinhua", R.string.jinhua);
		cityNamesMap.put("Jining1", R.string.jining1);
		cityNamesMap.put("Jining", R.string.jining);
		cityNamesMap.put("Jinjiang", R.string.jinjiang);
		cityNamesMap.put("Jintan", R.string.jintan);
		cityNamesMap.put("Jinzhong", R.string.jinzhong);
		cityNamesMap.put("Jinzhou", R.string.jinzhou);
		cityNamesMap.put("Jishou", R.string.jishou);
		cityNamesMap.put("Jiujiang", R.string.jiujiang);
		cityNamesMap.put("Jiuquan", R.string.jiuquan);
		cityNamesMap.put("Jixi", R.string.jixi);
		cityNamesMap.put("Jiyuan", R.string.jiyuan);
		cityNamesMap.put("Jurong", R.string.jurong);
		cityNamesMap.put("Kaifeng", R.string.kaifeng);
		cityNamesMap.put("Kaili", R.string.kaili);
		cityNamesMap.put("Kaiping", R.string.kaiping);
		cityNamesMap.put("Kaiyuan", R.string.kaiyuan);
		cityNamesMap.put("Kashen", R.string.kashen);
		cityNamesMap.put("Kelamayi", R.string.kelamayi);
		cityNamesMap.put("Kuerle", R.string.kuerle);
		cityNamesMap.put("Kuitun", R.string.kuitun);
		cityNamesMap.put("Kunming", R.string.kunming);
		cityNamesMap.put("Kunshan", R.string.kunshan);
		cityNamesMap.put("Laibin", R.string.laibin);
		cityNamesMap.put("Laiwu", R.string.laiwu);
		cityNamesMap.put("Laixi", R.string.laixi);
		cityNamesMap.put("Laizhou", R.string.laizhou);
		cityNamesMap.put("Langfang", R.string.langfang);
		cityNamesMap.put("Lanzhou", R.string.lanzhou);
		cityNamesMap.put("Lasa", R.string.lasa);
		cityNamesMap.put("Leshan", R.string.leshan);
		cityNamesMap.put("Lianyungang", R.string.lianyungang);
		cityNamesMap.put("Liaocheng", R.string.liaocheng);
		cityNamesMap.put("Liaoyang", R.string.liaoyang);
		cityNamesMap.put("Liaoyuan", R.string.liaoyuan);
		cityNamesMap.put("Lijiang", R.string.lijiang);
		cityNamesMap.put("Linan", R.string.linan);
		cityNamesMap.put("Lincang", R.string.lincang);
		cityNamesMap.put("Linfen", R.string.linfen);
		cityNamesMap.put("Lingbao", R.string.lingbao);
		cityNamesMap.put("Linhe", R.string.linhe);
		cityNamesMap.put("Linxia", R.string.linxia);
		cityNamesMap.put("Linyi", R.string.linyi);
		cityNamesMap.put("Lishui", R.string.lishui);
		cityNamesMap.put("Liuan", R.string.liuan);
		cityNamesMap.put("Liupanshui", R.string.liupanshui);
		cityNamesMap.put("Liuzhou", R.string.liuzhou);
		cityNamesMap.put("Liyang", R.string.liyang);
		cityNamesMap.put("Longhai", R.string.longhai);
		cityNamesMap.put("Longyan", R.string.longyan);
		cityNamesMap.put("Loudi", R.string.loudi);
		cityNamesMap.put("Luohe", R.string.luohe);
		cityNamesMap.put("Luoyang", R.string.luoyang);
		cityNamesMap.put("Luxi", R.string.luxi);
		cityNamesMap.put("Luzhou", R.string.luzhou);
		cityNamesMap.put("Lvliang", R.string.lvliang);
		cityNamesMap.put("Lvshun", R.string.lvshun);
		cityNamesMap.put("Maanshan", R.string.maanshan);
		cityNamesMap.put("Maoming", R.string.maoming);
		cityNamesMap.put("Meihekou", R.string.meihekou);
		cityNamesMap.put("Meishan", R.string.meishan);
		cityNamesMap.put("Meizhou", R.string.meizhou);
		cityNamesMap.put("Mianxian", R.string.mianxian);
		cityNamesMap.put("Mianyang", R.string.mianyang);
		cityNamesMap.put("Mudanjiang", R.string.mudanjiang);
		cityNamesMap.put("Nanan", R.string.nanan);
		cityNamesMap.put("Nanchang", R.string.nanchang);
		cityNamesMap.put("Nanchong", R.string.nanchong);
		cityNamesMap.put("Nanjing", R.string.nanjing);
		cityNamesMap.put("Nanning", R.string.nanning);
		cityNamesMap.put("Nanping", R.string.nanping);
		cityNamesMap.put("Nantong", R.string.nantong);
		cityNamesMap.put("Nanyang", R.string.nanyang);
		cityNamesMap.put("Neijiang", R.string.neijiang);
		cityNamesMap.put("Ningbo", R.string.ningbo);
		cityNamesMap.put("Ningde", R.string.ningde);
		cityNamesMap.put("Panjin", R.string.panjin);
		cityNamesMap.put("Panzhihua", R.string.panzhihua);
		cityNamesMap.put("Penglai", R.string.penglai);
		cityNamesMap.put("Pingdingshan", R.string.pingdingshan);
		cityNamesMap.put("Pingdu", R.string.pingdu);
		cityNamesMap.put("Pinghu", R.string.pinghu);
		cityNamesMap.put("Pingliang", R.string.pingliang);
		cityNamesMap.put("Pingxiang", R.string.pingxiang);
		cityNamesMap.put("Pulandian", R.string.pulandian);
		cityNamesMap.put("Puning", R.string.puning);
		cityNamesMap.put("Putian", R.string.putian);
		cityNamesMap.put("Puyang", R.string.puyang);
		cityNamesMap.put("Qiannan", R.string.qiannan);
		cityNamesMap.put("Qidong", R.string.qidong);
		cityNamesMap.put("Qingdao", R.string.qingdao);
		cityNamesMap.put("Qingyang", R.string.qingyang);
		cityNamesMap.put("Qingyuan", R.string.qingyuan);
		cityNamesMap.put("Qingzhou", R.string.qingzhou);
		cityNamesMap.put("Qinhuangdao", R.string.qinhuangdao);
		cityNamesMap.put("Qinzhou", R.string.qinzhou);
		cityNamesMap.put("Qionghai", R.string.qionghai);
		cityNamesMap.put("Qiqihaer", R.string.qiqihaer);
		cityNamesMap.put("Quanzhou", R.string.quanzhou);
		cityNamesMap.put("Qujing", R.string.qujing);
		cityNamesMap.put("Quzhou", R.string.quzhou);
		cityNamesMap.put("Rikaze", R.string.rikaze);
		cityNamesMap.put("Rizhao", R.string.rizhao);
		cityNamesMap.put("Rongcheng", R.string.rongcheng);
		cityNamesMap.put("Rugao", R.string.rugao);
		cityNamesMap.put("Ruian", R.string.ruian);
		cityNamesMap.put("Rushan", R.string.rushan);
		cityNamesMap.put("Sanmenxia", R.string.sanmenxia);
		cityNamesMap.put("Sanming", R.string.sanming);
		cityNamesMap.put("Sanya", R.string.sanya);
		cityNamesMap.put("Xiamen", R.string.xiamen);
		cityNamesMap.put("Shan", R.string.shan);
		cityNamesMap.put("Shangluo", R.string.shangluo);
		cityNamesMap.put("Shangqiu", R.string.shangqiu);
		cityNamesMap.put("Shangrao", R.string.shangrao);
		cityNamesMap.put("Shangyu", R.string.shangyu);
		cityNamesMap.put("Shantou", R.string.shantou);
		cityNamesMap.put("Ankang", R.string.ankang);
		cityNamesMap.put("Shaoguan", R.string.shaoguan);
		cityNamesMap.put("Shaoxing", R.string.shaoxing);
		cityNamesMap.put("Shaoyang", R.string.shaoyang);
		cityNamesMap.put("Shenyang", R.string.shenyang);
		cityNamesMap.put("Shenzhen", R.string.shenzhen);
		cityNamesMap.put("Shihezi", R.string.shihezi);
		cityNamesMap.put("Shijiazhuang", R.string.shijiazhuang);
		cityNamesMap.put("Shilin", R.string.shilin);
		cityNamesMap.put("Shishi", R.string.shishi);
		cityNamesMap.put("Shiyan", R.string.shiyan);
		cityNamesMap.put("Shouguang", R.string.shouguang);
		cityNamesMap.put("Shuangyashan", R.string.shuangyashan);
		cityNamesMap.put("Shuozhou", R.string.shuozhou);
		cityNamesMap.put("Shuyang", R.string.shuyang);
		cityNamesMap.put("Simao", R.string.simao);
		cityNamesMap.put("Siping", R.string.siping);
		cityNamesMap.put("Songyuan", R.string.songyuan);
		cityNamesMap.put("Suining", R.string.suining);
		cityNamesMap.put("Suizhou", R.string.suizhou);
		cityNamesMap.put("Suzhou", R.string.suzhou);
		cityNamesMap.put("Tacheng", R.string.tacheng);
		cityNamesMap.put("Taian", R.string.taian);
		cityNamesMap.put("Taicang", R.string.taicang);
		cityNamesMap.put("Taixing", R.string.taixing);
		cityNamesMap.put("Taiyuan", R.string.taiyuan);
		cityNamesMap.put("Taizhou", R.string.taizhou);
		cityNamesMap.put("Taizhou1", R.string.taizhou1);
		cityNamesMap.put("Tangshan", R.string.tangshan);
		cityNamesMap.put("Tengchong", R.string.tengchong);
		cityNamesMap.put("Tengzhou", R.string.tengzhou);
		cityNamesMap.put("Tianmen", R.string.tianmen);
		cityNamesMap.put("Tianshui", R.string.tianshui);
		cityNamesMap.put("Tieling", R.string.tieling);
		cityNamesMap.put("Tongchuan", R.string.tongchuan);
		cityNamesMap.put("Tongliao", R.string.tongliao);
		cityNamesMap.put("Tongling", R.string.tongling);
		cityNamesMap.put("Tonglu", R.string.tonglu);
		cityNamesMap.put("Tongren", R.string.tongren);
		cityNamesMap.put("Tongxiang", R.string.tongxiang);
		cityNamesMap.put("Tongzhou", R.string.tongzhou);
		cityNamesMap.put("Tonghua", R.string.tonghua);
		cityNamesMap.put("Tulufan", R.string.tulufan);
		cityNamesMap.put("Wafangdian", R.string.wafangdian);
		cityNamesMap.put("Weifang", R.string.weifang);
		cityNamesMap.put("Weihai", R.string.weihai);
		cityNamesMap.put("Weinan", R.string.weinan);
		cityNamesMap.put("Wendeng", R.string.wendeng);
		cityNamesMap.put("Wenling", R.string.wenling);
		cityNamesMap.put("Wenzhou", R.string.wenzhou);
		cityNamesMap.put("Wuhai", R.string.wuhai);
		cityNamesMap.put("Wuhan", R.string.wuhan);
		cityNamesMap.put("Wuhu", R.string.wuhu);
		cityNamesMap.put("Wujiang", R.string.wujiang);
		cityNamesMap.put("Wulanhaote", R.string.wulanhaote);
		cityNamesMap.put("Wuwei", R.string.wuwei);
		cityNamesMap.put("Wuxi", R.string.wuxi);
		cityNamesMap.put("Wuzhou", R.string.wuzhou);
		cityNamesMap.put("Xian", R.string.xian);
		cityNamesMap.put("Xiangcheng", R.string.xiangcheng);
		cityNamesMap.put("Xiangfan", R.string.xiangfan);
		cityNamesMap.put("Xianggelila", R.string.xianggelila);
		cityNamesMap.put("Xiangshan", R.string.xiangshan);
		cityNamesMap.put("Xiangtan", R.string.xiangtan);
		cityNamesMap.put("Xiangxiang", R.string.xiangxiang);
		cityNamesMap.put("Xianning", R.string.xianning);
		cityNamesMap.put("Xiantao", R.string.xiantao);
		cityNamesMap.put("Xianyang", R.string.xianyang);
		cityNamesMap.put("Xicang", R.string.xicang);
		cityNamesMap.put("Xichang", R.string.xichang);
		cityNamesMap.put("Xingtai", R.string.xingtai);
		cityNamesMap.put("Xingyi", R.string.xingyi);
		cityNamesMap.put("Xining", R.string.xining);
		cityNamesMap.put("Xinxiang", R.string.xinxiang);
		cityNamesMap.put("Xinyang", R.string.xinyang);
		cityNamesMap.put("Xinyu", R.string.xinyu);
		cityNamesMap.put("Xinzhou", R.string.xinzhou);
		cityNamesMap.put("Suqian", R.string.suqian);
		cityNamesMap.put("Suyu", R.string.suyu);
		cityNamesMap.put("Suzhou1", R.string.suzhou1);
		cityNamesMap.put("Xuancheng", R.string.xuancheng);
		cityNamesMap.put("Xuchang", R.string.xuchang);
		cityNamesMap.put("Xuzhou", R.string.xuzhou);
		cityNamesMap.put("Yaan", R.string.yaan);
		cityNamesMap.put("Yakeshi", R.string.yakeshi);
		cityNamesMap.put("Yanan", R.string.yanan);
		cityNamesMap.put("Yanbian", R.string.yanbian);
		cityNamesMap.put("Yancheng", R.string.yancheng);
		cityNamesMap.put("Yangjiang", R.string.yangjiang);
		cityNamesMap.put("Yangquan", R.string.yangquan);
		cityNamesMap.put("Yangzhou", R.string.yangzhou);
		cityNamesMap.put("Yanji", R.string.yanji);
		cityNamesMap.put("Yantai", R.string.yantai);
		cityNamesMap.put("Yanzhou", R.string.yanzhou);
		cityNamesMap.put("Yibin", R.string.yibin);
		cityNamesMap.put("Yichang", R.string.yichang);
		cityNamesMap.put("Yichun", R.string.yichun);
		cityNamesMap.put("Yichun1", R.string.yichun1);
		cityNamesMap.put("Yili", R.string.yili);
		cityNamesMap.put("Yinchuan", R.string.yinchuan);
		cityNamesMap.put("Yingkou", R.string.yingkou);
		cityNamesMap.put("Yingtan", R.string.yingtan);
		cityNamesMap.put("Yining", R.string.yining);
		cityNamesMap.put("Yiwu", R.string.yiwu);
		cityNamesMap.put("Yixing", R.string.yixing);
		cityNamesMap.put("Yiyang", R.string.yiyang);
		cityNamesMap.put("Yongkang", R.string.yongkang);
		cityNamesMap.put("Yongzhou", R.string.yongzhou);
		cityNamesMap.put("Yueyang", R.string.yueyang);
		cityNamesMap.put("Yuhuan", R.string.yuhuan);
		cityNamesMap.put("Yulin1", R.string.yulin1);
		cityNamesMap.put("Yulin", R.string.yulin);
		cityNamesMap.put("Yuncheng", R.string.yuncheng);
		cityNamesMap.put("Yuxi", R.string.yuxi);
		cityNamesMap.put("Yuyao", R.string.yuyao);
		cityNamesMap.put("Zaozhuang", R.string.zaozhuang);
		cityNamesMap.put("Zengcheng", R.string.zengcheng);
		cityNamesMap.put("Changchun", R.string.changchun);
		cityNamesMap.put("Changhai", R.string.changhai);
		cityNamesMap.put("Zhangjiagang", R.string.zhangjiagang);
		cityNamesMap.put("Zhangjiajie", R.string.zhangjiajie);
		cityNamesMap.put("Zhangjiakou", R.string.zhangjiakou);
		cityNamesMap.put("Changle", R.string.changle);
		cityNamesMap.put("Zhangqiu", R.string.zhangqiu);
		cityNamesMap.put("Changsha", R.string.changsha);
		cityNamesMap.put("Zhangye", R.string.zhangye);
		cityNamesMap.put("Changzhi", R.string.changzhi);
		cityNamesMap.put("Zhangzhou", R.string.zhangzhou);
		cityNamesMap.put("Zhanjiang", R.string.zhanjiang);
		cityNamesMap.put("Zhaodong", R.string.zhaodong);
		cityNamesMap.put("Zhaoqing", R.string.zhaoqing);
		cityNamesMap.put("Zhaotong", R.string.zhaotong);
		cityNamesMap.put("Zhengzhou", R.string.zhengzhou);
		cityNamesMap.put("Zhenjiang", R.string.zhenjiang);
		cityNamesMap.put("Zhongshan", R.string.zhongshan);
		cityNamesMap.put("Zhoukou", R.string.zhoukou);
		cityNamesMap.put("Zhoushan", R.string.zhoushan);
		cityNamesMap.put("Zhucheng", R.string.zhucheng);
		cityNamesMap.put("Zhuhai", R.string.zhuhai);
		cityNamesMap.put("Zhuji", R.string.zhuji);
		cityNamesMap.put("Zhumadian", R.string.zhumadian);
		cityNamesMap.put("Zhuzhou", R.string.zhuzhou);
		cityNamesMap.put("Zibo", R.string.zibo);
		cityNamesMap.put("Zigong", R.string.zigong);
		cityNamesMap.put("Zunyi", R.string.zunyi);
		cityNamesMap.put("Wulumuqi", R.string.wulumuqi);
		cityNamesMap.put("Fuqing", R.string.fuqing);
		cityNamesMap.put("Ezhou", R.string.ezhou);
		cityNamesMap.put("Baotou", R.string.baotou);
		cityNamesMap.put("Xiaoshan", R.string.xiaoshan);
		cityNamesMap.put("Xuanhua", R.string.xuanhua);
		cityNamesMap.put("Jiangyou", R.string.jiangyou);
		cityNamesMap.put("Ziyang", R.string.ziyang);
		cityNamesMap.put("Xinji", R.string.xinji);
		cityNamesMap.put("Foshan", R.string.foshan);
		cityNamesMap.put("Wanzhou", R.string.wanzhou);
		cityNamesMap.put("Zoucheng", R.string.zoucheng);
		cityNamesMap.put("Shaowu", R.string.shaowu);
		cityNamesMap.put("Jiangyan", R.string.jiangyan);
		cityNamesMap.put("Xiangyin", R.string.xiangyin);
		cityNamesMap.put("Hongkong", R.string.hongkong);
		
		
		cityNamesMap.put("Bangkok", R.string.bangkok);
	    cityNamesMap.put("Chaiyaphum", R.string.chaiyaphum );
	    cityNamesMap.put("Chanthaburi", R.string.chanthaburi );
	    cityNamesMap.put("Chiang Mai", R.string.chiangmai );
	    cityNamesMap.put("Chiang Rai", R.string.chiangrai );
	    cityNamesMap.put("Chonburi", R.string.chonburi );
	    cityNamesMap.put("Chumphon", R.string.chumphon );
		cityNamesMap.put("Haad Yai", R.string.haadyai );
		cityNamesMap.put("Hua Hin", R.string.huahin );
	    cityNamesMap.put("Kamphang", R.string.kamphang );
		cityNamesMap.put("Lampang", R.string.lampang );
		cityNamesMap.put("Lopburi", R.string.lopburi );
		cityNamesMap.put("Nakhon Pathom", R.string.nakhonpathom );
		cityNamesMap.put("Nakhon Sawan", R.string.nakhonsawan );
		cityNamesMap.put("Hongkong", R.string.nongkhai );
		cityNamesMap.put("Pattaya", R.string.pattaya );
		cityNamesMap.put("Phitsanulok", R.string.phitsanulok );
		cityNamesMap.put("Phuket", R.string.phuket );
		cityNamesMap.put("Saraburi", R.string.saraburi );
		cityNamesMap.put("Suphanburi", R.string.suphanburi );
		cityNamesMap.put("Song Khla", R.string.songkhla );
		cityNamesMap.put("Takhli", R.string.takhli );
		cityNamesMap.put("Udonthani", R.string.udonthani );
		cityNamesMap.put("Trang", R.string.trang);
		//省份
		cityNamesMap.put("Hebei", R.string.hebei);
		cityNamesMap.put("Shanxi", R.string.shanxi);
		cityNamesMap.put("Liaoning", R.string.liaoning);
		cityNamesMap.put("Heilongjiang", R.string.heilungkiang);
		cityNamesMap.put("Jiangsu", R.string.jiangsu);
		cityNamesMap.put("Zhejiang", R.string.zhejiang);
		cityNamesMap.put("Anhui", R.string.anhui);
		cityNamesMap.put("Fujian", R.string.fujian);
		cityNamesMap.put("Jiangxi", R.string.jiangxi);
		cityNamesMap.put("Shandong", R.string.shandong);
		cityNamesMap.put("Henan", R.string.henan);
		cityNamesMap.put("Hubei", R.string.hubei);
		cityNamesMap.put("Hunan", R.string.hunan);
		cityNamesMap.put("Guangdong", R.string.guangdong);
		cityNamesMap.put("Hainan", R.string.hainan);
		cityNamesMap.put("Sichuan", R.string.sichuan);
		cityNamesMap.put("Guizhou", R.string.guizhou);
		cityNamesMap.put("Yunnan", R.string.yunnan);
		cityNamesMap.put("Shaanxi", R.string.shaanxi);
		cityNamesMap.put("Gansu", R.string.gansu);
		cityNamesMap.put("Qinghai", R.string.qinghai);
		cityNamesMap.put("Taiwan", R.string.taiwan);
		cityNamesMap.put("Inner", R.string.inner);
		cityNamesMap.put("Guangxi", R.string.guangxi);
		cityNamesMap.put("Ningxia", R.string.ningxia);
		cityNamesMap.put("Xinjiang", R.string.xinjiang);
		cityNamesMap.put("Xizang", R.string.xizang);
		cityNamesMap.put("Macao", R.string.macao);
		
		
		//44种天气图标对应的，文字描述信息。
		
		icondescript.put(1, R.string.icon1);
		icondescript.put(2, R.string.icon2);
		icondescript.put(3, R.string.icon3);
		icondescript.put(4, R.string.icon4);
		icondescript.put(5, R.string.icon5);
		icondescript.put(6, R.string.icon6);
		icondescript.put(7, R.string.icon7);
		icondescript.put(8, R.string.icon8);
		icondescript.put(9, R.string.icon9);
		icondescript.put(10, R.string.icon10);
		icondescript.put(11, R.string.icon11);
		icondescript.put(12, R.string.icon12);
		icondescript.put(13, R.string.icon13);
		icondescript.put(14, R.string.icon14);
		icondescript.put(15, R.string.icon15);
		icondescript.put(16, R.string.icon16);
		icondescript.put(17, R.string.icon17);
		icondescript.put(18, R.string.icon18);
		icondescript.put(19, R.string.icon19);
		icondescript.put(20, R.string.icon20);
		icondescript.put(21, R.string.icon21);
		icondescript.put(22, R.string.icon22);
		icondescript.put(23, R.string.icon23);
		icondescript.put(24, R.string.icon24);
		icondescript.put(25, R.string.icon25);
		icondescript.put(26, R.string.icon26);
		icondescript.put(27, R.string.icon27);
		icondescript.put(28, R.string.icon28);
		icondescript.put(29, R.string.icon29);
		icondescript.put(30, R.string.icon30);
		icondescript.put(31, R.string.icon31);
		icondescript.put(32, R.string.icon32);
		icondescript.put(33, R.string.icon33);
		icondescript.put(34, R.string.icon34);
		icondescript.put(35, R.string.icon35);
		icondescript.put(36, R.string.icon36);
		icondescript.put(37, R.string.icon37);
		icondescript.put(38, R.string.icon38);
		icondescript.put(39, R.string.icon39);
		icondescript.put(40, R.string.icon40);
		icondescript.put(41, R.string.icon41);
		icondescript.put(42, R.string.icon42);
		icondescript.put(43, R.string.icon43);
		icondescript.put(44, R.string.icon44);
		
		//44种天气对应的特效图标
		
		iconsMap.put(101, R.drawable.sunny_day);
		iconsMap.put(102, R.drawable.sunny_day);
		iconsMap.put(103, R.drawable.sunny_day);
		iconsMap.put(104, R.drawable.sunny_day);
		iconsMap.put(105, R.drawable.sunny_day);
		iconsMap.put(106, R.drawable.cloudy_day_sky);
		iconsMap.put(107, R.drawable.cloudy_day_sky);
		iconsMap.put(108, R.drawable.cloudy_day_sky);
		iconsMap.put(111, R.drawable.sunny_day);
		iconsMap.put(112, R.drawable.rain_day_sky);
		iconsMap.put(113, R.drawable.rain_day_sky);
		iconsMap.put(114, R.drawable.rain_day_sky);
		iconsMap.put(115, R.drawable.rain_day_sky);
		iconsMap.put(116, R.drawable.rain_day_sky);
		iconsMap.put(117, R.drawable.rain_day_sky);
		iconsMap.put(118, R.drawable.rain_day_sky);
		iconsMap.put(119, R.drawable.snow_day_sky);
		iconsMap.put(120, R.drawable.snow_day_sky);
		iconsMap.put(121, R.drawable.snow_day_sky);
		iconsMap.put(122, R.drawable.snow_day_sky);
		iconsMap.put(123, R.drawable.snow_day_sky);
		iconsMap.put(124, R.drawable.snow_day_sky);
		iconsMap.put(125, R.drawable.snow_day_sky);
		iconsMap.put(126, R.drawable.rain_day_sky);		
		iconsMap.put(129, R.drawable.snow_day_sky);
		iconsMap.put(130, R.drawable.sunny_day);
		iconsMap.put(131, R.drawable.sunny_day);
		iconsMap.put(132, R.drawable.sunny_day);
		iconsMap.put(133, R.drawable.sunny_day);
		iconsMap.put(134, R.drawable.sunny_day);
		iconsMap.put(135, R.drawable.sunny_day);
		iconsMap.put(136, R.drawable.sunny_day);
		iconsMap.put(137, R.drawable.sunny_day);
		iconsMap.put(138, R.drawable.cloudy_day_sky);
		iconsMap.put(139, R.drawable.rain_day_sky);
		iconsMap.put(140, R.drawable.rain_day_sky);
		iconsMap.put(141, R.drawable.rain_day_sky);
		iconsMap.put(142, R.drawable.rain_day_sky);
		iconsMap.put(143, R.drawable.snow_day_sky);
		iconsMap.put(144, R.drawable.snow_day_sky);
//		
		iconsMap.put(201, R.drawable.sunny_day_land);
		iconsMap.put(202, R.drawable.sunny_day_land);
		iconsMap.put(203, R.drawable.sunny_day_land);
		iconsMap.put(204, R.drawable.sunny_day_land);
		iconsMap.put(205, R.drawable.sunny_day_land);
		iconsMap.put(206, R.drawable.cloudy_day_land);
		iconsMap.put(207, R.drawable.cloudy_day_land);
		iconsMap.put(208, R.drawable.cloudy_day_land);
		iconsMap.put(211, R.drawable.sunny_day_land);
		iconsMap.put(212, R.drawable.rain_day_land);
		iconsMap.put(213, R.drawable.rain_day_land);
		iconsMap.put(214, R.drawable.rain_day_land);
		iconsMap.put(215, R.drawable.rain_day_land);
		iconsMap.put(216, R.drawable.rain_day_land);
		iconsMap.put(217, R.drawable.rain_day_land);
		iconsMap.put(218, R.drawable.rain_day_land);
		iconsMap.put(219, R.drawable.snow_day_land);
		iconsMap.put(220, R.drawable.snow_day_land);
		iconsMap.put(221, R.drawable.snow_day_land);
		iconsMap.put(222, R.drawable.snow_day_land);
		iconsMap.put(223, R.drawable.snow_day_land);
		iconsMap.put(224, R.drawable.snow_day_land);
		iconsMap.put(225, R.drawable.snow_day_land);
		iconsMap.put(226, R.drawable.rain_day_land);
		iconsMap.put(229, R.drawable.snow_day_land);
		iconsMap.put(230, R.drawable.sunny_day_land);
		iconsMap.put(231, R.drawable.sunny_day_land);
		iconsMap.put(232, R.drawable.sunny_day_land);
		iconsMap.put(233, R.drawable.sunny_day_land);
		iconsMap.put(234, R.drawable.sunny_day_land);
		iconsMap.put(235, R.drawable.sunny_day_land);
		iconsMap.put(236, R.drawable.sunny_day_land);
		iconsMap.put(237, R.drawable.sunny_day_land);
		iconsMap.put(238, R.drawable.cloudy_day_land);
		iconsMap.put(239, R.drawable.rain_day_land);
		iconsMap.put(240, R.drawable.rain_day_land);
		iconsMap.put(241, R.drawable.rain_day_land);
		iconsMap.put(242, R.drawable.rain_day_land);
		iconsMap.put(243, R.drawable.snow_day_land);
		iconsMap.put(244, R.drawable.snow_day_land);
		
//		iconsMap.put(401, R.drawable.accu_301);
//		iconsMap.put(402, R.drawable.accu_302);
//		iconsMap.put(403, R.drawable.accu_303);
//		iconsMap.put(404, R.drawable.accu_302);
//		iconsMap.put(405, R.drawable.accu_303);
//		iconsMap.put(406, R.drawable.accu_306);
//		iconsMap.put(407, R.drawable.accu_306);
//		iconsMap.put(408, R.drawable.accu_302);
//		iconsMap.put(411, R.drawable.accu_311);
		iconsMap.put(412, R.drawable.rain_day);
		iconsMap.put(413, R.drawable.rain_day);
		iconsMap.put(414, R.drawable.rain_day);
		iconsMap.put(415, R.drawable.rain_day);
		iconsMap.put(416, R.drawable.rain_day);
		iconsMap.put(417, R.drawable.rain_day);
		iconsMap.put(418, R.drawable.rain_day);
		iconsMap.put(419, R.drawable.snow_day);
		iconsMap.put(420, R.drawable.snow_day);
		iconsMap.put(421, R.drawable.snow_day);
		iconsMap.put(422, R.drawable.snow_day);
		iconsMap.put(423, R.drawable.snow_day);
		iconsMap.put(424, R.drawable.snow_day);
		iconsMap.put(425, R.drawable.snow_day);
//		iconsMap.put(426, R.drawable.snow_day);
		iconsMap.put(429, R.drawable.snow_day);
//		iconsMap.put(430, R.drawable.accu_330);
//		iconsMap.put(431, R.drawable.accu_226);
//		iconsMap.put(432, R.drawable.accu_119);
//		iconsMap.put(433, R.drawable.accu_333);
//		iconsMap.put(434, R.drawable.accu_303);
//		iconsMap.put(435, R.drawable.accu_303);
//		iconsMap.put(436, R.drawable.accu_303);
//		iconsMap.put(437, R.drawable.accu_311);
//		iconsMap.put(438, R.drawable.accu_302);
		iconsMap.put(439, R.drawable.rain_day);
		iconsMap.put(440, R.drawable.rain_day);
		iconsMap.put(441, R.drawable.rain_day);
		iconsMap.put(442, R.drawable.rain_day);
		iconsMap.put(443, R.drawable.snow_day);
		iconsMap.put(444, R.drawable.snow_day);
		
		iconsMap.put(151, R.drawable.sunny_night);
		iconsMap.put(152, R.drawable.sunny_night);
		iconsMap.put(153, R.drawable.sunny_night);
		iconsMap.put(154, R.drawable.sunny_night);
		iconsMap.put(155, R.drawable.sunny_night);
		iconsMap.put(156, R.drawable.cloudy_night_sky);
		iconsMap.put(157, R.drawable.cloudy_night_sky);
		iconsMap.put(158, R.drawable.cloudy_night_sky);
		iconsMap.put(161, R.drawable.sunny_night);
		iconsMap.put(162, R.drawable.rain_night_sky);
		iconsMap.put(163, R.drawable.rain_night_sky);
		iconsMap.put(164, R.drawable.rain_night_sky);
		iconsMap.put(165, R.drawable.rain_night_sky);
		iconsMap.put(166, R.drawable.rain_night_sky);
		iconsMap.put(167, R.drawable.rain_night_sky);
		iconsMap.put(168, R.drawable.rain_night_sky);
		iconsMap.put(169, R.drawable.snow_night_sky);
		iconsMap.put(170, R.drawable.snow_night_sky);
		iconsMap.put(171, R.drawable.snow_night_sky);
		iconsMap.put(172, R.drawable.snow_night_sky);
		iconsMap.put(173, R.drawable.snow_night_sky);
		iconsMap.put(174, R.drawable.snow_night_sky);
		iconsMap.put(175, R.drawable.snow_night_sky);
		iconsMap.put(176, R.drawable.rain_night_sky);		
		iconsMap.put(179, R.drawable.snow_night_sky);
		iconsMap.put(180, R.drawable.sunny_night);
		iconsMap.put(181, R.drawable.sunny_night);
		iconsMap.put(182, R.drawable.sunny_night);
		iconsMap.put(183, R.drawable.sunny_night);
		iconsMap.put(184, R.drawable.sunny_night);
		iconsMap.put(185, R.drawable.sunny_night);
		iconsMap.put(186, R.drawable.sunny_night);
		iconsMap.put(187, R.drawable.sunny_night);
		iconsMap.put(188, R.drawable.cloudy_night_sky);
		iconsMap.put(189, R.drawable.rain_night_sky);
		iconsMap.put(190, R.drawable.rain_night_sky);
		iconsMap.put(191, R.drawable.rain_night_sky);
		iconsMap.put(192, R.drawable.rain_night_sky);
		iconsMap.put(193, R.drawable.snow_night_sky);
		iconsMap.put(194, R.drawable.snow_night_sky);
//		
		iconsMap.put(251, R.drawable.sunny_night_land);
		iconsMap.put(252, R.drawable.sunny_night_land);
		iconsMap.put(253, R.drawable.sunny_night_land);
		iconsMap.put(254, R.drawable.sunny_night_land);
		iconsMap.put(255, R.drawable.sunny_night_land);
		iconsMap.put(256, R.drawable.cloudy_night_land);
		iconsMap.put(257, R.drawable.cloudy_night_land);
		iconsMap.put(258, R.drawable.cloudy_night_land);
		iconsMap.put(261, R.drawable.sunny_night_land);
		iconsMap.put(262, R.drawable.rain_night_land);
		iconsMap.put(263, R.drawable.rain_night_land);
		iconsMap.put(264, R.drawable.rain_night_land);
		iconsMap.put(265, R.drawable.rain_night_land);
		iconsMap.put(266, R.drawable.rain_night_land);
		iconsMap.put(267, R.drawable.rain_night_land);
		iconsMap.put(268, R.drawable.rain_night_land);
		iconsMap.put(269, R.drawable.snow_night_land);
		iconsMap.put(270, R.drawable.snow_night_land);
		iconsMap.put(271, R.drawable.snow_night_land);
		iconsMap.put(272, R.drawable.snow_night_land);
		iconsMap.put(273, R.drawable.snow_night_land);
		iconsMap.put(274, R.drawable.snow_night_land);
		iconsMap.put(275, R.drawable.snow_night_land);
		iconsMap.put(276, R.drawable.rain_night_land);
		iconsMap.put(279, R.drawable.snow_night_land);
		iconsMap.put(280, R.drawable.sunny_night_land);
		iconsMap.put(281, R.drawable.sunny_night_land);
		iconsMap.put(282, R.drawable.sunny_night_land);
		iconsMap.put(283, R.drawable.sunny_night_land);
		iconsMap.put(284, R.drawable.sunny_night_land);
		iconsMap.put(285, R.drawable.sunny_night_land);
		iconsMap.put(286, R.drawable.sunny_night_land);
		iconsMap.put(287, R.drawable.sunny_night_land);
		iconsMap.put(288, R.drawable.cloudy_night_land);
		iconsMap.put(289, R.drawable.rain_night_land);
		iconsMap.put(290, R.drawable.rain_night_land);
		iconsMap.put(291, R.drawable.rain_night_land);
		iconsMap.put(292, R.drawable.rain_night_land);
		iconsMap.put(293, R.drawable.snow_night_land);
		iconsMap.put(294, R.drawable.snow_night_land);
		
//		iconsMap.put(451, R.drawable.accu_301);
//		iconsMap.put(452, R.drawable.accu_302);
//		iconsMap.put(453, R.drawable.accu_303);
//		iconsMap.put(454, R.drawable.accu_302);
//		iconsMap.put(455, R.drawable.accu_303);
//		iconsMap.put(456, R.drawable.accu_306);
//		iconsMap.put(457, R.drawable.accu_306);
//		iconsMap.put(458, R.drawable.accu_302);
//		iconsMap.put(461, R.drawable.accu_311);
		iconsMap.put(462, R.drawable.rain_night);
		iconsMap.put(463, R.drawable.rain_night);
		iconsMap.put(464, R.drawable.rain_night);
		iconsMap.put(465, R.drawable.rain_night);
		iconsMap.put(466, R.drawable.rain_night);
		iconsMap.put(467, R.drawable.rain_night);
		iconsMap.put(468, R.drawable.rain_night);
		iconsMap.put(469, R.drawable.snow_night);
		iconsMap.put(470, R.drawable.snow_night);
		iconsMap.put(471, R.drawable.snow_night);
		iconsMap.put(472, R.drawable.snow_night);
		iconsMap.put(473, R.drawable.snow_night);
		iconsMap.put(474, R.drawable.snow_night);
		iconsMap.put(475, R.drawable.snow_night);
		iconsMap.put(476, R.drawable.rain_night);
		iconsMap.put(479, R.drawable.snow_night);
//		iconsMap.put(470, R.drawable.accu_330);
//		iconsMap.put(481, R.drawable.accu_226);
//		iconsMap.put(482, R.drawable.accu_119);
//		iconsMap.put(483, R.drawable.accu_333);
//		iconsMap.put(484, R.drawable.accu_303);
//		iconsMap.put(485, R.drawable.accu_303);
//		iconsMap.put(486, R.drawable.accu_303);
//		iconsMap.put(487, R.drawable.accu_311);
//		iconsMap.put(488, R.drawable.accu_302);
		iconsMap.put(489, R.drawable.rain_night);
		iconsMap.put(490, R.drawable.rain_night);
		iconsMap.put(491, R.drawable.rain_night);
		iconsMap.put(492, R.drawable.rain_night);
//		iconsMap.put(493, R.drawable.snow_night);
//		iconsMap.put(494, R.drawable.snow_night);

		
		iconsMap.put(301, R.drawable.common_m_weather_01);
		iconsMap.put(302, R.drawable.common_m_weather_02);
		iconsMap.put(303, R.drawable.common_m_weather_03);
		iconsMap.put(304, R.drawable.common_m_weather_04);
		iconsMap.put(305, R.drawable.common_m_weather_05);
		iconsMap.put(306, R.drawable.common_m_weather_06);
		iconsMap.put(307, R.drawable.common_m_weather_07);
		iconsMap.put(308, R.drawable.common_m_weather_08);
		iconsMap.put(311, R.drawable.common_m_weather_11);
		iconsMap.put(312, R.drawable.common_m_weather_12);
		iconsMap.put(313, R.drawable.common_m_weather_13);
		iconsMap.put(314, R.drawable.common_m_weather_14);
		iconsMap.put(315, R.drawable.common_m_weather_15);
		iconsMap.put(316, R.drawable.common_m_weather_16);
		iconsMap.put(317, R.drawable.common_m_weather_17);
		iconsMap.put(318, R.drawable.common_m_weather_18);
		iconsMap.put(319, R.drawable.common_m_weather_19);
		iconsMap.put(320, R.drawable.common_m_weather_20);
		iconsMap.put(321, R.drawable.common_m_weather_21);
		iconsMap.put(322, R.drawable.common_m_weather_22);
		iconsMap.put(323, R.drawable.common_m_weather_23);
		iconsMap.put(324, R.drawable.common_m_weather_24);
		iconsMap.put(325, R.drawable.common_m_weather_25);
		iconsMap.put(326, R.drawable.common_m_weather_26);		
		iconsMap.put(329, R.drawable.common_m_weather_29);
		iconsMap.put(330, R.drawable.common_m_weather_30);
		iconsMap.put(331, R.drawable.common_m_weather_31);
		iconsMap.put(332, R.drawable.common_m_weather_32);
		iconsMap.put(333, R.drawable.common_m_weather_33);
		iconsMap.put(334, R.drawable.common_m_weather_34);
		iconsMap.put(335, R.drawable.common_m_weather_35);
		iconsMap.put(336, R.drawable.common_m_weather_36);
		iconsMap.put(337, R.drawable.common_m_weather_37);
		iconsMap.put(338, R.drawable.common_m_weather_38);
		iconsMap.put(339, R.drawable.common_m_weather_39);
		iconsMap.put(340, R.drawable.common_m_weather_40);
		iconsMap.put(341, R.drawable.common_m_weather_41);
		iconsMap.put(342, R.drawable.common_m_weather_42);
		iconsMap.put(343, R.drawable.common_m_weather_43);
		iconsMap.put(344, R.drawable.common_m_weather_44);
		
		
//		iconsMap.put(1001, R.drawable.accu_broom);
//		iconsMap.put(1002, R.drawable.accu_hand);
//		iconsMap.put(1003, R.drawable.accu_man);
		
		
		
		
		
//		iconNamesMap.put(101, "accu_101");
//		iconNamesMap.put(102, "accu_101");
//		iconNamesMap.put(103, "accu_101");
//		iconNamesMap.put(104, "accu_101");
//		iconNamesMap.put(105, "accu_101");
//		iconNamesMap.put(106, "accu_106");
//		iconNamesMap.put(107, "accu_106");
//		iconNamesMap.put(108, "accu_101");
//		iconNamesMap.put(111, "accu_111");
//		iconNamesMap.put(112, "accu_118");
//		iconNamesMap.put(113, "accu_113");
//		iconNamesMap.put(114, "accu_118");
//		iconNamesMap.put(115, "accu_115");
//		iconNamesMap.put(116, "accu_115");
//		iconNamesMap.put(117, "accu_115");
//		iconNamesMap.put(118, "accu_118");
//		iconNamesMap.put(119, "accu_119");
//		iconNamesMap.put(120, "accu_119");
//		iconNamesMap.put(121, "accu_119");
//		iconNamesMap.put(122, "accu_223");
//		iconNamesMap.put(123, "accu_123");
//		iconNamesMap.put(124, "accu_124");
//		iconNamesMap.put(125, "accu_223");
//		iconNamesMap.put(126, "accu_126");
//		iconNamesMap.put(129, "accu_223");
//		iconNamesMap.put(130, "accu_130");
//		iconNamesMap.put(131, "accu_126");
//		iconNamesMap.put(132, "accu_119");
//		iconNamesMap.put(133, "accu_133");
//		iconNamesMap.put(134, "accu_101");
//		iconNamesMap.put(135, "accu_101");
//		iconNamesMap.put(136, "accu_101");
//		iconNamesMap.put(137, "accu_111");
//		iconNamesMap.put(138, "accu_101");
//		iconNamesMap.put(139, "accu_113");
//		iconNamesMap.put(140, "accu_113");
//		iconNamesMap.put(141, "accu_115");
//		iconNamesMap.put(142, "accu_115");
//		iconNamesMap.put(143, "accu_101");
//		iconNamesMap.put(144, "accu_123");
//		
//		iconNamesMap.put(201, "accu_201");
//		iconNamesMap.put(202, "accu_201");
//		iconNamesMap.put(203, "accu_201");
//		iconNamesMap.put(204, "accu_201");
//		iconNamesMap.put(205, "accu_201");
//		iconNamesMap.put(206, "accu_106");
//		iconNamesMap.put(207, "accu_106");
//		iconNamesMap.put(208, "accu_201");
//		iconNamesMap.put(211, "accu_111");
//		iconNamesMap.put(212, "accu_118");
//		iconNamesMap.put(213, "accu_118");
//		iconNamesMap.put(214, "accu_118");
//		iconNamesMap.put(215, "accu_215");
//		iconNamesMap.put(216, "accu_215");
//		iconNamesMap.put(217, "accu_215");
//		iconNamesMap.put(218, "accu_218");
//		iconNamesMap.put(219, "accu_119");
//		iconNamesMap.put(220, "accu_119");
//		iconNamesMap.put(221, "accu_119");
//		iconNamesMap.put(222, "accu_223");
//		iconNamesMap.put(223, "accu_223");
//		iconNamesMap.put(224, "accu_124");
//		iconNamesMap.put(225, "accu_225");
//		iconNamesMap.put(226, "accu_226");
//		iconNamesMap.put(229, "accu_225");
//		iconNamesMap.put(230, "accu_230");
//		iconNamesMap.put(231, "accu_226");
//		iconNamesMap.put(232, "accu_119");
//		iconNamesMap.put(233, "accu_233");
//		iconNamesMap.put(234, "accu_201");
//		iconNamesMap.put(235, "accu_201");
//		iconNamesMap.put(236, "accu_201");
//		iconNamesMap.put(237, "accu_111");
//		iconNamesMap.put(238, "accu_201");
//		iconNamesMap.put(239, "accu_118");
//		iconNamesMap.put(240, "accu_118");
//		iconNamesMap.put(241, "accu_215");
//		iconNamesMap.put(242, "accu_215");
//		iconNamesMap.put(243, "accu_201");
//		iconNamesMap.put(244, "accu_223");
		
		iconNamesMap.put(301, "accu_301");
		iconNamesMap.put(302, "accu_302");
		iconNamesMap.put(303, "accu_303");
		iconNamesMap.put(304, "accu_302");
		iconNamesMap.put(305, "accu_303");
		iconNamesMap.put(306, "accu_306");
		iconNamesMap.put(307, "accu_306");
		iconNamesMap.put(308, "accu_302");
		iconNamesMap.put(311, "accu_311");
		iconNamesMap.put(312, "accu_212");
		iconNamesMap.put(313, "accu_212");
		iconNamesMap.put(314, "accu_212");
		iconNamesMap.put(315, "accu_315");
		iconNamesMap.put(316, "accu_315");
		iconNamesMap.put(317, "accu_315");
		iconNamesMap.put(318, "accu_218");
		iconNamesMap.put(319, "accu_119");
		iconNamesMap.put(320, "accu_119");
		iconNamesMap.put(321, "accu_119");
		iconNamesMap.put(322, "accu_222");
		iconNamesMap.put(323, "accu_323");
		iconNamesMap.put(324, "accu_224");
		iconNamesMap.put(325, "accu_325");
		iconNamesMap.put(326, "accu_226");
		iconNamesMap.put(329, "accu_325");
//		iconNamesMap.put(330, "accu_330");
		iconNamesMap.put(331, "accu_226");
		iconNamesMap.put(332, "accu_119");
//		iconNamesMap.put(333, "accu_333");
		iconNamesMap.put(334, "accu_303");
		iconNamesMap.put(335, "accu_303");
		iconNamesMap.put(336, "accu_303");
		iconNamesMap.put(337, "accu_311");
		iconNamesMap.put(338, "accu_302");
		iconNamesMap.put(339, "accu_212");
		iconNamesMap.put(340, "accu_212");
		iconNamesMap.put(341, "accu_315");
		iconNamesMap.put(342, "accu_315");
		iconNamesMap.put(343, "accu_302");
		iconNamesMap.put(344, "accu_323");
		
		
		iconNamesMap.put(1001, "accu_broom");
		iconNamesMap.put(1002, "accu_hand");
		iconNamesMap.put(1003, "accu_man");
		
		
//		weekiconsMap.put("Mon", R.drawable.week_mon);
//		weekiconsMap.put("Tue", R.drawable.week_tue);
//		weekiconsMap.put("Wed", R.drawable.week_wed);
//		weekiconsMap.put("Thu", R.drawable.week_thu);
//		weekiconsMap.put("Fri", R.drawable.week_fri);
//		weekiconsMap.put("Sat", R.drawable.week_sat);
//		weekiconsMap.put("Sun", R.drawable.week_sun);
//		
//		weekiconsMap.put("Mo ", R.drawable.week_de_mon);
//		weekiconsMap.put("Di ", R.drawable.week_de_tue);
//		weekiconsMap.put("Mi ", R.drawable.week_de_wed);
//		weekiconsMap.put("Do ", R.drawable.week_de_thu);
//		weekiconsMap.put("Fr ", R.drawable.week_de_fri);
//		weekiconsMap.put("Sa ", R.drawable.week_de_sat);
//		weekiconsMap.put("So ", R.drawable.week_de_sun);
		
		weekiconsMap.put("1", R.drawable.flip_0);
		weekiconsMap.put("2", R.drawable.flip_0);
		weekiconsMap.put("3", R.drawable.flip_0);
		weekiconsMap.put("4", R.drawable.flip_0);
		
		
		digit_iconsMap.put('0', R.drawable.flip_0);
		digit_iconsMap.put('1', R.drawable.flip_1);
		digit_iconsMap.put('2', R.drawable.flip_2);
		digit_iconsMap.put('3', R.drawable.flip_3);
		digit_iconsMap.put('4', R.drawable.flip_4);
		digit_iconsMap.put('5', R.drawable.flip_5);
		digit_iconsMap.put('6', R.drawable.flip_6);
		digit_iconsMap.put('7', R.drawable.flip_7);
		digit_iconsMap.put('8', R.drawable.flip_8);
		digit_iconsMap.put('9', R.drawable.flip_9);		
		
		digit_iconsMap.put('\u0966', R.drawable.flip_0);
		digit_iconsMap.put('\u0967', R.drawable.flip_1);
		digit_iconsMap.put('\u0968', R.drawable.flip_2);
		digit_iconsMap.put('\u0969', R.drawable.flip_3);
		digit_iconsMap.put('\u096a', R.drawable.flip_4);
		digit_iconsMap.put('\u096b', R.drawable.flip_5);
		digit_iconsMap.put('\u096c', R.drawable.flip_6);
		digit_iconsMap.put('\u096d', R.drawable.flip_7);
		digit_iconsMap.put('\u096e', R.drawable.flip_8);
		digit_iconsMap.put('\u096f', R.drawable.flip_9);	
		
		digit_iconsMap.put('\u06F0', R.drawable.flip_0);
		digit_iconsMap.put('\u06F1', R.drawable.flip_1);
		digit_iconsMap.put('\u06F2', R.drawable.flip_2);
		digit_iconsMap.put('\u06F3', R.drawable.flip_3);
		digit_iconsMap.put('\u06F4', R.drawable.flip_4);
		digit_iconsMap.put('\u06F5', R.drawable.flip_5);
		digit_iconsMap.put('\u06F6', R.drawable.flip_6);
		digit_iconsMap.put('\u06F7', R.drawable.flip_7);
		digit_iconsMap.put('\u06F8', R.drawable.flip_8);
		digit_iconsMap.put('\u06F9', R.drawable.flip_9);
		
		digit_iconsMap.put('\u0660', R.drawable.flip_0);
		digit_iconsMap.put('\u0661', R.drawable.flip_1);
		digit_iconsMap.put('\u0662', R.drawable.flip_2);
		digit_iconsMap.put('\u0663', R.drawable.flip_3);
		digit_iconsMap.put('\u0664', R.drawable.flip_4);
		digit_iconsMap.put('\u0665', R.drawable.flip_5);
		digit_iconsMap.put('\u0666', R.drawable.flip_6);
		digit_iconsMap.put('\u0667', R.drawable.flip_7);
		digit_iconsMap.put('\u0668', R.drawable.flip_8);
		digit_iconsMap.put('\u0669', R.drawable.flip_9);		
	
//		0 ०  
//		1 १
//		2 २
//
//		3 ३
//		4 ४
//		5 ५
//		6 ६
//		7 ७
//		8 ८
//		9 ९
	
		
		
		
		
		
	}
	
	private AccuIconMapper() {
	}
	
	public static int getDrawableIdByIconId(Integer iconCode) {
		Integer code = iconsMap.get(iconCode);
		if(code==null)
		{			
				return 0;			
		}
		return code;
	}
	
	public static int getBackByIconId(Integer iconCode) {
		Integer code = iconsMap.get(iconCode);
		if(code==null)
		{
			if(iconCode>200)
				return R.drawable.flip_0;
			else
				return R.drawable.flip_1;
		}
		return code;
	}
	
	
	public static int getWeatherDescription(int iconid){
		if(iconid>44||iconid<1)
			return icondescript.get(9);
		return icondescript.get(iconid);
		
		
	}
	
	
	public static int getCityName(String week) {
		Integer code;
		if(week.contains(" ")){
			int tmpint = week.indexOf(" ");
			String tmpstr = week.substring(0, tmpint)+week.substring(tmpint, week.length());
			 code = cityNamesMap.get(tmpstr);
		}
		else
		 code = cityNamesMap.get(week);
		
		return code != null ? code : 0;
	}
	
	public static int getDrawableIdByIconId(String week) {
		Integer code = weekiconsMap.get(week);
		return code != null ? code : R.drawable.accu_302;
	}
	
	public static int getDrawableIdByIconId(Character iconCode) {
		Integer code = digit_iconsMap.get(iconCode);
		return code != null ? code : R.drawable.accu_302;
	}
	public static String getFileNameById(int iconId)
	{
		String te =iconNamesMap.get(iconId);
		if(te==null){
			if(iconId>200)
				return "accu_201";
			else
				return "accu_101";
		}
		return te;
	}
}
