package com.all.weather;

public enum Setting {
	PREFERENCE_WEATHER_TYPE,
	PREFERENCE_LOCATION_TYPE,
    PREFERENCE_DATASRC_TYPE,
    
	PREFERENCE_ACUU_LOCATION_ZIP,
	PREFERENCE_ACUU_LOCATION_ZIP_W, 
    PREFERENCE_ACUU_LOCATION_CITY,	
	PREFERENCE_ACUU_LOCATION_CITY_W,
	PREFERENCE_ACUU_LOCATION_AREA,
	PREFERENCE_ACUU_LOCATION_AREA_W,
	
	PREFERENCE_CENTER_LOCATION_ZIP,
	PREFERENCE_CENTER_LOCATION_ZIP_W,
	PREFERENCE_CENTER_LOCATION_CITY,
	PREFERENCE_CENTER_LOCATION_CITY_W,
	PREFERENCE_CENTER_LOCATION_AREA,
	PREFERENCE_CENTER_LOCATION_AREA_W,
	
//	PREFERENCE_GOOGLE_LOCATION_ZIP,
//	PREFERENCE_GOOGLE_LOCATION_ZIP_W,
	PREFERENCE_GOOGLE_LOCATION_CITY,
	PREFERENCE_GOOGLE_LOCATION_CITY_W,
//	PREFERENCE_CENTER_LOCATION_AREA,
//	PREFERENCE_CENTER_LOCATION_AREA_W,	
	
//	PREFERENCE_LOCATION_STATE,
//	PREFERENCE_UPDATE_METHOD, 
//	PREFERENCE_UPDATE_INTERVAL,
	PREFERENCE_TEMPERATUREUNIT,
	PREFERENCE_UNIT;
}
